Update shape_template Add exceptions, assertion, input handler

diff --git a/.github/workflows/ci_workflow.yml b/.github/workflows/ci_workflow.yml
--- a/.github/workflows/ci_workflow.yml
+++ b/.github/workflows/ci_workflow.yml
@@ -1,59 +1,29 @@
 name: shape_template CI
-
 on:
   push:
 
 jobs:
-  build:
+  test:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-
-      - name: Run script
-        run: |
-          mkdir -p build
-          { ./run_shapes.sh > ./build/run.log 2>&1 || { echo "Script failed" && exit 1; }; }
-          cat ./build/run.log
-
-      - name: Upload run log file
-        uses: actions/upload-artifact@v4
-        with:
-          name: run-log-file
-          path: build/run.log
-
-      - name: Upload log file on failure
-        if: failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: script-log-file
-          path: ./build/f_script.log
-
-  make:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
 
       - name: Install g++
         run: sudo apt-get update && sudo apt-get install -y g++
 
       - name: Run Makefile (make all)
-        run: make all
-
-  docker:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Run Docker build/test
         run: |
-          mkdir -p build
-          { ./run_shapes.sh Docker > ./build/docker.log 2>&1 || { echo "Script failed" && exit 1; }; }
-          cat ./build/docker.log
+          make all
 
+      - name: Docker build/test
+        run: |
+          set -e  # exit immediately on error
+          docker build . --file Dockerfile --tag ci_workflow > ./build/docker.log 2>&1
+          docker run --rm ci_workflow circle 10
+      
       - name: Upload log file on failure
         if: failure()
         uses: actions/upload-artifact@v4
         with:
-          name: docker-log-file
-          path: ./build/f_docker.log
+          name: log-file
+          path: ./build/log-file.log
